app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Email

from app.models import User


class LoginForm(FlaskForm):
	username = StringField('Username:', validators=[DataRequired()])
	password = PasswordField('Password:', validators=[DataRequired()])
	remember_me = BooleanField('Lembrar-me:')
	submit = SubmitField('Entrar')


class RegistrationForm(FlaskForm):
	username = StringField('Username:', validators=[DataRequired()])
	email = StringField('Email:', validators=[DataRequired(), Email()])
	password = PasswordField('Password:', validators=[DataRequired()])
	password2 = PasswordField('Confirmar Password:', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Registar')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user is not None:
			raise ValidationError('Porfavor utilize um username diferente.')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user is not None:
			raise ValidationError('Porfavor utilize um email diferente.')


class EditForm(FlaskForm):
	username = StringField('Username:', validators=[DataRequired()])
	email = StringField('Email:', validators=[DataRequired(), Email()])
	password = PasswordField('Confirmar Password:', validators=[DataRequired()])
	avatar = FileField(validators=[FileAllowed('image', 'Image only!')])
	banner = FileField(validators=[FileAllowed('image', 'Image only!')])
	submit = SubmitField('Editar')

app/main/controllers.py
import os

from flask import render_template, redirect, url_for, Blueprint
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.utils import secure_filename

from app import db
from app.admin_mod.views import media_prefix_uuid
from app.main.forms import LoginForm, RegistrationForm, EditForm
from app.models import User, Anime

# Define the blueprint: 'main', set its url prefix: app.url/
from config import STATIC

main = Blueprint('main', __name__, url_prefix='/')


@main.route('/', methods=['GET'])
def home():
	animes = Anime.query.all()
	return render_template('main/index.html', title='Home', animes=animes)


@main.route('/user/<int:id>')
def profile(id: id):
	user = User.query.filter_by(id=id).first_or_404()
	return render_template('main/user_profile.html', title=user.username, user=user)


@main.route('/user/edit', methods=['GET', 'POST'])
@login_required
def edit_profile():
	form = EditForm()
	if form.validate_on_submit():
		return redirect(url_for('main.profile', id=current_user.id))
	form.email.data = current_user.email
	return render_template('main/edit_profile.html', title='Editar Prefil', form=form)


@main.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user is None or not user.check_password(form.password.data):
			return redirect(url_for('main.login'))

		login_user(user, remember=form.remember_me.data)
		return redirect(url_for('main.home'))
	return render_template('main/login.html', title='Sign In', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(username=form.username.data, email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		return redirect(url_for('main.login'))
	return render_template('main/register.html', title='Register', form=form)


@main.route('/logout', methods=['GET'])
@login_required
def logout():
	logout_user()
	return redirect(url_for('main.home'))

app/templates/main/edit_profile.html
{% extends 'admin/model/edit.html' %}

{% block body %}
    <h1>TODO</h1>
    {{ super() }}
{% endblock %}

app/templates/main/index.html
{% extends "_layout.html" %}
{% block body %}
	{% for anime in animes %}
		<h1 class="text-red">{{ anime.name }}</h1>
	{% endfor %}
{% endblock %}

app/templates/main/login.html
{% extends "_layout.html" %}
{% block body_nnb %}
	<div class="d-flex flex-column justify-content-center hv100">
		<div class="m-auto p-3">
			<a href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='texto.png') }}" width="100%" style="padding:10px 0 50px 0;"></a>
			<div class="bg-0f0f0f px-3 pt-3 pb-2 w-100">
				<form enctype="multipart/form-data" method="post" class="d-flex justify-content-center flex-column text-white" novalidate>
					{{ form.hidden_tag() }}
					{{ form.non_field_errors }}

					{{ form.username.label }}
					{{ form.username(class="w-100 input-hover mb-2") }}
					{{ form.password.label }}
					{{ form.password(class="w-100 input-hover mb-4") }}
					{{ form.remember_me.label }}
					{{ form.remember_me(id="cbx", style="display:none") }}
					<label for="cbx" class="toggle"><span></span></label>

					<div class="d-flex justify-content-center pt-4">{{ form.submit(class="submit-btn mx-auto") }}</div>
					<p class="fs-12 mb-0">
						<a href="{{ url_for('main.register') }}" class="text-white hover-no-underline red-hover">Não tens conta?</a>
					</p>
				</form>
			</div>

		</div>
	</div>
{% endblock %}

app/templates/main/register.html
{% extends "_layout.html" %}
{% block body_nnb %}
	<div class="d-flex flex-column justify-content-center hv100">
		<div class="m-auto p-3">
			<a href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='texto.png') }}" width="100%" style="padding:10px 0 50px 0;"></a>
			<div class="bg-0f0f0f px-3 pt-3 pb-2 w-100">
				<form enctype="multipart/form-data" method="post" class="d-flex justify-content-center flex-column text-white" novalidate>
					{{ form.hidden_tag() }}
					{{ form.non_field_errors }}

					{{ form.username.label }}
					{{ form.username(class="w-100 input-hover mb-2") }}
					{{ form.email.label }}
					{{ form.email(class="w-100 input-hover mb-2") }}
					{{ form.password.label }}
					{{ form.password(class="w-100 input-hover mb-2") }}
					{{ form.password2.label }}
					{{ form.password2(class="w-100 input-hover mb-2") }}

					<div class="d-flex justify-content-center pt-4">{{ form.submit(class="submit-btn mx-auto") }}</div>
					<p class="fs-12 mb-0">
						<a href="{{ url_for('main.login') }}" class="text-white hover-no-underline red-hover">Já tens conta?</a>
					</p>
				</form>
			</div>

		</div>
	</div>
{% endblock %}

app/templates/main/user_profile.html
{% extends "_layout.html" %}
{% block body %}

	<div class="">
		<div class="">
			<img src="{% if user.banner %}{{ url_for('static', filename=user.banner) }}{% else %}{{ url_for('static', filename='no_banner.png') }}{% endif %}" alt="" width="100%" height="auto" style="border-radius: 0 0 150px 150px">
		</div>
		<div class="position-relative mx-5 px-5" style="top:-95px">
			<div class="row no-gutters mx-5">
				<img src="{% if user.avatar %}{{ url_for('static', filename=user.avatar) }}{% else %}{{ url_for('static', filename='no_avatar.png') }}{% endif %}" alt="" height="190px" width="190px"
				     class="rounded-circle d-none d-lg-block z-above">
				<div class="col d-flex align-items-center">
					<div class="d-none d-lg-block">
						<div class="bg-white position-relative" style="left:-95px;padding:10px 25px 10px 95px;border-radius: 150px">
							<h2 class="red-underline ml-2 text-dark" style="max-width: 320px;overflow: hidden">{{ user.username }}</h2>
							{% if user.is_admin %}<h5 class="text-red ml-2">Admin</h5>{% else %}<h5 class="text-success ml-2">Membro</h5>{% endif %}
						</div>
					</div>
					<div class="d-block d-lg-none pt-5 mt-4 mx-auto">
						<div class="bg-white" style="padding:5px 25px 5px 25px;border-radius: 150px">
							<h2 class="text-dark text-center fs-16"><span class="red-underline">{{ user.username }}</span></h2>
							{% if user.is_admin %}<h5 class="text-center text-red fs-12 mb-0">Admin</h5>{% else %}<h5 class="text-success mb-0">Membro</h5>{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div>
			{% if user.id == current_user.id %}
				<a href="{{ url_for('main.edit_profile') }}" class="btn btn-success">Edit Profile</a>
			{% endif %}

			<h1 class="text-white">TESTE TESTE TESTE</h1>
		</div>
	</div>

{% endblock %}