app/anime_mod/controllers.py
import json

from flask import render_template, Blueprint
from flask_login import login_required, current_user

from app import db
from app.models import Anime, Episode, UserRatedEpisodes

# Define the blueprint: 'anime_mod', set its url prefix: app.url/
anime_mod = Blueprint('anime_mod', __name__, url_prefix='/')


@anime_mod.route('/animes')
def animes():
	animes = Anime.query.order_by(Anime.id).limit(10).all()
	return render_template('anime/index.html', title='Animes', animes=animes)


@anime_mod.route('/a/<int:id>')
def anime_details(id: int):
	anime = Anime.query.get_or_404(id)
	categories = ", ".join([x.name for x in anime.genres])
	return render_template('anime/anime_detail.html', title=anime.name, anime=anime, categories=categories)


@anime_mod.route('/v/<int:id>')
def episode(id: int):
	episode = Episode.query.get_or_404(id)
	next_epis = Episode.query.filter(Episode.number > episode.number).limit(10).all()
	anterior = Episode.query.filter(Episode.number < episode.number).order_by(Episode.number).first()

	rate = None
	if current_user.is_authenticated:
		rate = current_user.rated_episodes.filter_by(episode_id=id).first()
	like = rate.liked if rate else False
	dislike = rate.disliked if rate else False

	return render_template('anime/episode_detail.html', title=episode.__str__(), episode=episode, next=next_epis, before=anterior, liked=like, disliked=dislike)


@login_required
@anime_mod.route('/like/<int:id>', methods=['GET'])
def like_episode(id: int):
	if not current_user.is_authenticated:
		return json.dumps(""), 401, {'ContentType': 'application/json'}

	row = current_user.rated_episodes.filter_by(episode_id=id).first()

	# Row doesn't exist in DB
	if not row:
		obj = UserRatedEpisodes(user_id=current_user.id, episode_id=id, liked=True, disliked=False)
		current_user.rated_episodes.append(obj)
		db.session.commit()
		return json.dumps({'success': True, 'liked': True, 'disliked': False}), 200, {'ContentType': 'application/json'}

	# Row exists in db
	else:
		row.liked = liked = not row.liked
		row.disliked = False
		db.session.commit()
		return json.dumps({'success': True, 'liked': liked, 'disliked': False}), 200, {'ContentType': 'application/json'}


@login_required
@anime_mod.route('/dislike/<int:id>', methods=['GET'])
def dislike_episode(id: int):
	if not current_user.is_authenticated:
		return json.dumps(""), 401, {'ContentType': 'application/json'}

	row = current_user.rated_episodes.filter_by(episode_id=id).first()

	# Row doesn't exist in DB
	if not row:
		obj = UserRatedEpisodes(user_id=current_user.id, episode_id=id, liked=False, disliked=True)
		current_user.rated_episodes.append(obj)
		db.session.commit()
		return json.dumps({'success': True, 'disliked': True, 'liked': False}), 200, {'ContentType': 'application/json'}

	# Row exists in db
	else:
		row.liked = False
		row.disliked = disliked = not row.disliked
		db.session.commit()
		return json.dumps({'success': True, 'disliked': disliked, 'liked': False}), 200, {'ContentType': 'application/json'}

app/main/controllers.py
import os

from flask import render_template, redirect, url_for, Blueprint
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.utils import secure_filename

from app import db
from app.admin_mod.views import media_prefix_uuid
from app.main.forms import LoginForm, RegistrationForm, EditForm
from app.models import User, Anime

# Define the blueprint: 'main', set its url prefix: app.url/
from config import STATIC

main = Blueprint('main', __name__, url_prefix='/')


@main.route('/', methods=['GET'])
def home():
	animes = Anime.query.all()
	return render_template('main/index.html', title='Home', animes=animes)


@main.route('/user/<int:id>')
def profile(id: id):
	user = User.query.filter_by(id=id).first_or_404()
	return render_template('main/user_profile.html', title=user.username, user=user)


@main.route('/user/edit', methods=['GET', 'POST'])
@login_required
def edit_profile():
	form = EditForm()
	if form.validate_on_submit():
		return redirect(url_for('main.profile', id=current_user.id))
	form.email.data = current_user.email
	return render_template('main/edit_profile.html', title='Editar Prefil', form=form)


@main.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if user is None or not user.check_password(form.password.data):
			return redirect(url_for('main.login'))

		login_user(user, remember=form.remember_me.data)
		return redirect(url_for('main.home'))
	return render_template('main/login.html', title='Sign In', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(username=form.username.data, email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		return redirect(url_for('main.login'))
	return render_template('main/register.html', title='Register', form=form)


@main.route('/logout', methods=['GET'])
@login_required
def logout():
	logout_user()
	return redirect(url_for('main.home'))

app/templates/_layout.html
<!doctype html>
<html lang="pt">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>{{ title }}</title>
	<meta name="description" content="AnimeGalaxy, o seu melhor lugar para ver animes!">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}" media="." onload="this.media='all'">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" media="." onload="this.media='all'">
	<link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" media="." onload="this.media='all'">
	<link rel="shortcut icon" type="image/x-icon" href={{ url_for("static", filename="favicon.ico") }}>
</head>

<body class="bg-dark-gradient hv100" style="background: #0F0F0F; visibility: hidden" onload="ready()">
{% block body_nnb %}

	<img src="{{ url_for('static', filename='top_banner.png') }}" alt="" width="100%" height="auto">

	<!-- NavBar -->
	<nav class="navbar navbar-expand-md navbar-dark bg-0f0f0f p-0 sticky-top">
		<div class="container mt-0 px-0">
			<!-- Logo -->
			<a class="navbar-brand" href="{{ url_for('main.home') }}">
				<img src="{{ url_for('static', filename='texto.png') }}" height="45" width="auto">
			</a>
			<!-- Toggler -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
					class="navbar-toggler-icon"></span>
			</button>
			<!-- Item List -->
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link p-0 hover-grey" href="{{ url_for('anime_mod.animes') }}">
							<img src="{{ url_for('static', filename='animes_button.png') }}" style="height: 65px" />
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link p-0 hover-grey" href="#">
							<img src="{{ url_for('static', filename='team_button.png') }}" style="height: 65px" />
						</a>
					</li>
				</ul>
				<!-- Dropdown -->
				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle d-flex align-items-center hover-grey" href="#" id="navbardrop" data-toggle="dropdown"
						   style="height: 65px">
							{% if current_user.is_authenticated %}
								<img src="{% if current_user.avatar %}{{ url_for('static', filename=current_user.avatar) }}{% else %}{{ url_for('static', filename='no_avatar.png') }}{% endif %}" style="height: 45px; width:45px"
								     class="rounded-circle mx-2" />
								{{ current_user.username }}
							{% else %}
								<img src="{{ url_for('static', filename='no_avatar.png') }}" style="height: 45px" class="rounded-circle mx-2" />
							{% endif %}
						</a>
						<div class="dropdown-menu">
							{% if current_user.is_authenticated %}
								{% if current_user.is_admin %}
									<a class="dropdown-item" href="{{ url_for('admin.index') }}"> <i class="fa fa-columns fa-fw" aria-hidden="true"></i>&nbspAdmin Panel</a>
								{% endif %}
								<a class="dropdown-item" href="{{ url_for('main.profile', id=current_user.id) }}"> <i class="fa fa-cogs fa-fw" aria-hidden="true"></i>&nbspPerfil</a>
								<a class="dropdown-item" href="{{ url_for('main.logout') }}"> <i class="fa fa-sign-out-alt fa-fw" aria-hidden="true"></i>&nbspSair</a>
							{% else %}
								<a class="dropdown-item" href="{{ url_for('main.register') }}"> <i class="fa fa-user-plus fa-fw" aria-hidden="true"></i>&nbspRegistrar</a>
								<a class="dropdown-item" href="{{ url_for('main.login') }}"> <i class="fa fa-sign-in-alt fa-fw" aria-hidden="true"></i>&nbspEntrar</a>
							{% endif %}
						</div>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- Body -->
	<div class="container mt-0 px-0">
		{% block body %}{% endblock %}
	</div>
{% endblock %}
	<!-- Scripts -->

<script defer src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js"></script>
<script defer>function ready() {
    document.body.setAttribute("style", "visibility:visible");
}</script>
{% block scripts %}
{% endblock %}
</body>
</html>